import Head from "next/head";
import styles from "./Index.module.css";
import Link from "next/link";
import settings from "@/settings.js";

export default function Home() {

  const user = { username: "USERNAME da SILVA" };
  // const user = null;


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={styles.page}
      >
        <main className={styles.main}>
          <img src="/logo.png" alt="logo" />
          <p>Pixel Place</p>
          <Link className={styles.btn} href={user ? "/place" : "/login"}>Começar</Link>
          <Link className={styles.btn} href="/partners">Servidores</Link>
        </main>

      <div className={styles.footer}>
        <p>Developed by <Link href={"https://nemtudo.me"}>NemTudo</Link>  <Link href={"https://commbat.com.br"}>commbat</Link></p>
      </div>
      </div>
    </>
  );
}
